name: CleanArchWithUIKitDemo

############
# Options
############

options:
  bundleIdPrefix: com.jill.app
  deploymentTarget:
    iOS: 17.0

############
# Settings
############

settings:
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: 'YES'
  ENABLE_USER_SCRIPT_SANDBOXING: 'YES'    

############
# Schemes
############

schemes:
  CleanArchWithUIKitDemo:
    build:
      targets:
        CleanArchWithUIKitDemo: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CleanArchWithUIKitDemoTests
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

############
# Targets
############

targets:
  CleanArchWithUIKitDemo:
    type: application
    platform: iOS
    sources:
      - path: CleanArchWithUIKitDemo
    settings:
      base:
        INFOPLIST_FILE: CleanArchWithUIKitDemo/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jill.app.CleanArchWithUIKitDemo

  CleanArchWithUIKitDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CleanArchWithUIKitDemoTests
    dependencies:
      - target: CleanArchWithUIKitDemo 
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES