name: CleanArchWithUIKitDemo

############
# Options
############

options:
  bundleIdPrefix: com.jill.app
  deploymentTarget:
    iOS: 17.0

############
# Targets
############

targets:
  CleanArchWithUIKitDemo:
    type: application
    platform: iOS
    sources:
      - path: CleanArchWithUIKitDemo
    settings:
      base:
        INFOPLIST_FILE: CleanArchWithUIKitDemo/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.jill.app.CleanArchWithUIKitDemo